#!/bin/sh

# Need to set the locale to C if reading in binary mode
#export LC_ALL=C

od -v -t u1 $1 | awk \
    -f load_asc.awk \
    -f util.awk \
    -f mem.awk \
    -f hdr.awk \
    -f stack.awk \
    -f var.awk \
    -f cpu.awk \
    -f txt.awk \
    -f tok.awk \
    -f obj.awk \
    -f rnd.awk \
    -f op.awk \
    -f z.awk \
