#!/bin/sh
export LC_ALL=C
awk \
    -f util.awk \
    -f mem.awk \
    -f hdr.awk \
    -f stack.awk \
    -f var.awk \
    -f cpu.awk \
    -f txt.awk \
    -f obj.awk \
    -f op.awk \
    -f z.awk \
    $*
